variables:
  REGISTRY: quay.io
  NAME: go-keycloak-proxy

stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  image: golang:1.6.0
  script:
    - make deps
    - make test

build:
  stage: build
  image: golang:1.6.0
  script:
    - make deps
    - make static
  artifacts:
    paths:
    - bin/
  only:
    - /^master$/
    - /^v([0-9]{1,3}[.]?){3}.*$/

deploy:
  stage: deploy
  script:
    - export VERSION=$CI_BUILD_TAG
    - '[[ "$VERSION" == "master" ]] && VERSION="latest"'
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN} -e ${REGISTRY_EMAIL} ${REGISTRY}
    - docker build -t ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION} .
    - docker push ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION}
    - docker rmi ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION}
  only:
    - /^master$/
    - /^v([0-9]{1,3}[.]?){3}.*$/
